//* isalnum	Check if character is alphanumeric (function)
//* isalpha	Check if character is alphabetic (function)
//* isspace	Check if character is a white-space (function)
//* isdigit	Check if character is decimal digit (function)
//* isxdigit	Check if character is hexadecimal digit (function)
//* islower	Check if character is lowercase letter (function)
//* isupper	Check if character is uppercase letter (function)
// isblank	Check if character is blank (function)
// isprint	Check if character is printable (function)
// ispunct	Check if character is a punctuation character (function)
// iscntrl	Check if character is a control character (function)
// isgraph	Check if character has graphical representation (function)

//* tolower	Convert uppercase letter to lowercase (function)
//* toupper	Convert lowercase letter to uppercase (function)
