//* isalnum	Check if character is alphanumeric (function)
//* isalpha	Check if character is alphabetic (function)
//* isdigit	Check if character is decimal digit (function)
//* isspace	Check if character is a white-space (function)
//* isblank	Check if character is blank (function)
//! ispunct	Check if character is a punctuation character (function) // !@#$,./;'"| "punctuation"
// isprint	Check if character is printable (function)
// isxdigit	Check if character is hexadecimal digit (function)
// iscntrl	Check if character is a control character (function)
// isgraph	Check if character has graphical representation (function)

//* islower	Check if character is lowercase letter (function)
//* isupper	Check if character is uppercase letter (function)
//* tolower	Convert uppercase letter to lowercase (function)
//* toupper	Convert lowercase letter to uppercase (function)
